#!/bin/bash

echo "use 'celery info' to show info message"
echo "use 'celery beat' to start beat service"

if [ "$1" == "beat" ]; then
  python -m celery -A PaperFives beat
elif [ "$1" == "info" ]; then
  python -m celery -A PaperFives worker -l info
else
  python -m celery -A PaperFives worker
fi
