DEFAULT_AVATAR_PATH: /static/avatar/default.png
INVALID_NAME_LIST:
  - default
  - admin
  - null
  - none
ERROR_CODE:
  SUCCESS: 0
  WRONG_REQUEST_METHOD: 10001
  BAD_REQUEST: 10002
  CREATE_USER: 11001