PROJECT_PATH: .
AVATAR_PATH: /media/avatar/
DEFAULT_AVATAR: /media/avatar/default.svg
IMG_MSG_PATH: /media/msg/
DEFAULT_IMG_MSG: /media/msg/default.png
PAPER_PATH: ../papers/

INVALID_NAME_LIST:
  - default
  - admin
  - null
  - none

ERROR_CODE:
  SUCCESS: 0
  SERVER_ERROR: 10111
  PAGE_NOT_FOUND: 10110
  WRONG_REQUEST_METHOD: 10001
  BAD_REQUEST: 10002
  NOT_AUTHORIZED: 10003

  SEND_EMAIL: 11001
  NOT_VERIFIED: 11002
  DUPLICATE_USER: 11003

  ALREADY_LOGGED_IN: 12001
  NO_SUCH_USER: 12002
  WRONG_PASSWORD: 12003
  NOT_LOGGED_IN: 12004

  FOLLOW_SELF: 13001
  FOLLOW_NOTHING: 13002

  MESSAGE_SELF: 14001

  NOT_YOUR_PAPER: 15001
  NOT_LEAD: 15002
  NO_SUCH_PAPER: 15003
  NOT_COMPLETE: 15004
  PERM_DENIED: 15005
  FILE_MISSING: 15006
  NOT_PUBLISHABLE: 15007
  NOT_EDITABLE: 15008
  NOT_REVIEWABLE: 15008
  NOT_CONFIRMABLE: 15008
  SEARCH_ERROR: 15009

  PAPER_EXISTS: 16001
