DEFAULT_AVATAR_PATH: /static/avatar/default.png
INVALID_NAME_LIST:
  - default
  - admin
  - null
  - none
ERROR_CODE:
  SUCCESS: 0
  WRONG_REQUEST_METHOD: 10001
  BAD_REQUEST: 10002
  NO_AUTH: 10003
  SEND_EMAIL: 11001
  NOT_VERIFIED: 11002
  DUPLICATE_USER: 11003
  ALREADY_LOGGED_IN: 12001
  NO_SUCH_USER: 12002
  WRONG_PASSWORD: 12003
  CREATE_USER: 11002